name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-docker:
    strategy:
      fail-fast: true
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2025-24.04
            artifact-name: Athena
            build-options: "-Ponlylinuxathena"
          - container: wpilib/raspbian-cross-ubuntu:bookworm-24.04
            artifact-name: Arm32
            build-options: "-Ponlylinuxarm32"
          - container: wpilib/aarch64-cross-ubuntu:bookworm-24.04
            artifact-name: Arm64
            build-options: "-Ponlylinuxarm64"
          - container: wpilib/ubuntu-base:24.04
            artifact-name: Linux
            build-options: "-Ponlylinuxx86-64"
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew build -PreleaseMode -PnoTests ${{ matrix.build-options }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-host:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            build-options: "-Ponlywindowsx86-64"
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew build -PreleaseMode -PnoTests ${{ matrix.build-options }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  push:
    name: Push to Main
    needs: [build-docker, build-host]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Releases
        uses: actions/checkout@v4
        with:
          ref: releases # Just to confirm that I am using the default branch
          path: releases
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
      - name: Checkout Build Tools
        uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools
          path: build-tools
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Vendordep Json
        working-directory: master
        run: ./gradlew vendordepJson
      - uses: actions/download-artifact@v4
        with:
          path: build-tools/combiner/products/build/allOutputs
      - name: Flatten Artifacts
        working-directory: build-tools/combiner/products/build/allOutputs
        run: rsync -a --delete ./*/* ./
      - name: Combine
        run: ./gradlew publish -Pthirdparty -PreleaseRepoPublish
        working-directory: build-tools/combiner
      - name: Copy releases
        run: |
          cp master/build/repos/*.json ./releases
          cp -r ~/releases/maven/release/* ./releases
      - name: Push to branch
        working-directory: releases
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[bot] Update releases"
          git push
